//! Keep `COMMANDS` in sync with `command_handlers!` in `src/commands/mod.rs`.
//! Listing them here flips Tauri ACL from “every window may invoke everything”
//! to deny-by-default; each capability then opts in with `allow-<kebab-name>`.

fn main() {
    // Snake_case command names → autogenerated `allow-foo-bar` / `deny-foo-bar`.
    const COMMANDS: &[&str] = &[
        // recording
        "list_capture_sources",
        "list_capture_devices",
        "list_microphones",
        "warm_microphone",
        "cool_microphone",
        "platform_capabilities",
        "check_permissions",
        "request_screen_permission",
        "open_screen_recording_settings",
        "relaunch",
        "recorder_state",
        "prepare_window_capture",
        "start_recording",
        "pause_recording",
        "resume_recording",
        "set_recording_mic_muted",
        "stop_recording",
        "pick_capture_area",
        "complete_area_pick",
        "cancel_area_pick",
        "show_area_frame_guide",
        "hide_area_frame_guide",
        "mark_camera_started",
        "begin_camera_file",
        "write_camera_chunk",
        "finish_camera_file",
        "hide_recorder",
        "set_recorder_layout",
        "set_recorder_bar_width",
        "set_recorder_bar_hitbox",
        "recorder_menu_space",
        "set_recorder_menu",
        "set_recorder_menu_live",
        "begin_recorder_drag",
        "end_recorder_drag",
        "show_camera_preview",
        "hide_camera_preview",
        "dismiss_camera_preview",
        "set_camera_preview_visible",
        "arm_camera_capture",
        "flush_camera_capture",
        "show_annotation_overlay",
        "hide_annotation_overlay",
        "set_annotation_display_follow",
        "open_library",
        "open_editor",
        "present_window",
        // system fonts
        "list_system_fonts",
        // captions
        "get_whisper_model_status",
        "download_whisper_model",
        "delete_whisper_model",
        "generate_captions",
        // projects
        "list_projects",
        "load_project",
        "ensure_proxy",
        "ensure_camera_track",
        "save_editor_state",
        "rename_project",
        "delete_project",
        "ensure_thumbnail",
        // custom backgrounds
        "save_custom_background",
        "list_custom_backgrounds",
        "delete_custom_background",
        // export
        "ensure_seekable_recording",
        "check_export_disk_space",
        "begin_export",
        "write_export_chunk",
        "finish_export",
        "abort_export",
        "begin_export_h264_stream",
        "write_export_h264_chunk",
        "finish_export_h264_stream",
        "abort_export_h264_stream",
        "begin_export_rawvideo_stream",
        "write_export_rawvideo_frame",
        "finish_export_rawvideo_stream",
        "abort_export_rawvideo_stream",
        "mux_export_audio",
        "prepare_export_audio",
        "attach_export_audio",
        "remove_temp_file",
        // error log
        "log_client_error",
        "log_client_info",
        "reveal_error_log",
        "reveal_logs_dir",
        "error_log_path",
        // updater
        "check_for_updates",
        "install_update",
        "dismiss_update",
        "cancel_install",
        "pending_update",
    ];

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
